parameters:
#    blog_main.example.class: Blog\MainBundle\Example

services:
#    blog_main.example:
#        class: %blog_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
